In [1]:
import numpy as np

In [2]:
#Init var
nbr_noeud = 4
dist_max = 10
Gamma = 0.5
Q = 0.5
alpha = 1
beta = 1
rho = 0.5
nb_k = 10 # nbr de fourmis
start = 0

In [3]:
mat_dist = np.random.randint(1,dist_max, size = (nbr_noeud,nbr_noeud))
np.fill_diagonal(mat_dist, 0)
print(mat_dist)

[[0 5 5 1]
 [3 0 5 9]
 [6 3 0 3]
 [8 5 1 0]]


In [4]:
mat_visited = [[start] for i in range(nb_k)]
#Ville n'ayant pas encore été visitée
def get_ville(mat_visited, nbr_noeud, k):
    all_ville = np.arange(nbr_noeud)
    return np.setdiff1d(all_ville, mat_visited[k])

ville = get_ville(mat_visited, nbr_noeud,0)

In [5]:
ville

array([1, 2, 3])

In [6]:
mat_phe = np.zeros((nbr_noeud,nbr_noeud))
mat_prob = np.zeros((nbr_noeud,nbr_noeud))
mat_vis = 1/mat_dist
np.fill_diagonal(mat_vis, 0)
mat_visited = [[start] for i in range(nb_k)]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [7]:
def get_probij(i,j,k):
    Gamma = np.random.rand()
    mat_probij = Gamma + np.power(mat_phe[i,j], alpha) + np.power(mat_vis[i,j], beta)
    kallowed = get_ville(mat_visited, nbr_noeud, k)
    summ = sum([Gamma + np.power(mat_phe[i,l], alpha) + np.power(mat_vis[i,l], beta) for l in kallowed])
    return mat_probij/summ
get_probij(0,1,0)

0.2549865094927949

In [8]:
def run(i,k,mat_visited):
    while len(mat_visited[k]) != nbr_noeud:
        mat_proba = []
        villeallowed = get_ville(mat_visited, nbr_noeud, k)
        for ville in villeallowed:
            mat_proba.append(get_probij(i,ville,k))
        nextville = villeallowed[np.argmax(np.asarray(mat_proba))]
        mat_visited[k].append(nextville)
        #print(mat_visited[k])
        #print(mat_proba)
        i = nextville
    return(mat_visited[k])

In [9]:
print(run(start,1,mat_visited))

[0, 3, 2, 1]


In [10]:
def longueurtrjt(trajet):
    villeav = start
    distance = 0
    for ville in trajet:
        if ville != start:
            distance += mat_dist[villeav,ville]
            villeav = ville
    distance += mat_dist[villeav,start]
    return distance

In [11]:
def run_all(start, k, mat_phe):
    for step in range(nb_k):
        mat_visited = [[start] for i in range(nb_k)]
        mat_visited[k] = run(start,k,mat_visited)
        #print(mat_visited[k])
        villeav = start
        for ville in mat_visited[k]:
            if ville != start:
                mat_phe[villeav, ville] += Q/longueurtrjt(mat_visited[k]) 
                villeav = ville
    return mat_phe

In [12]:
mat_phe = np.zeros((nbr_noeud,nbr_noeud))
for i in range(10):
    mat_phe = rho * run_all(start,i, mat_phe)
    print(mat_phe)

[[0.     0.     0.     0.3125]
 [0.     0.     0.     0.    ]
 [0.     0.3125 0.     0.    ]
 [0.     0.     0.3125 0.    ]]
[[0.         0.11904762 0.         0.15625   ]
 [0.         0.         0.11904762 0.        ]
 [0.         0.15625    0.         0.11904762]
 [0.         0.         0.15625    0.        ]]
[[0.         0.05952381 0.         0.390625  ]
 [0.         0.         0.05952381 0.        ]
 [0.         0.390625   0.         0.05952381]
 [0.         0.         0.390625   0.        ]]
[[0.        0.0297619 0.        0.5078125]
 [0.        0.        0.0297619 0.       ]
 [0.        0.5078125 0.        0.0297619]
 [0.        0.        0.5078125 0.       ]]
[[0.         0.01488095 0.         0.56640625]
 [0.         0.         0.01488095 0.        ]
 [0.         0.56640625 0.         0.01488095]
 [0.         0.         0.56640625 0.        ]]
[[0.         0.00744048 0.         0.59570312]
 [0.         0.         0.00744048 0.        ]
 [0.         0.59570312 0.         0.0074

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in double_scalars
  


In [13]:
import pygame

WHITE =     (255, 255, 255)
BLUE =      (  0,   0, 255)
GREEN =     (  0, 255,   0)
RED =       (255,   0,   0)
TEXTCOLOR = (  0,   0,  0)
(width, height) = (200, 300)

running = True

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html


In [14]:
def main():
    global running, screen

    pygame.init()
    screen = pygame.display.set_mode((width, height))
    pygame.display.set_caption("TUFF")
    screen.fill(WHITE)
    pygame.display.update()

    while running:
        ev = pygame.event.get()

        for event in ev:

            if event.type == pygame.MOUSEBUTTONUP:
                drawCircle()
                pygame.display.update()

            if event.type == pygame.QUIT:
                running = False

In [15]:
def getPos():
    pos = pygame.mouse.get_pos()
    return (pos)

def drawCircle():
    pos=getPos()
    pygame.draw.circle(screen, BLUE, (30,30), 20)
    pygame.draw.circle(screen, BLUE, (width - 30,30), 20)
    pygame.draw.circle(screen, BLUE, (30,int(width/2)), 20)
    pygame.draw.circle(screen, BLUE, (width - 30,int(width/2)), 20)
    pygame.draw.circle(screen, GREEN, (int(width/2),height - 30), 20)
def drawlines():
    pygame.draw.line(screen, (0, 0, 255), (int(width/2),int(height/2)), (width - 30,height - 30))

In [16]:
main()

In [30]:
print(mat_dist)

[[0 5 4 5]
 [6 0 9 9]
 [4 9 0 6]
 [9 8 4 0]]
