# TP Fourmis (Find Path)

#### Importation des librairies

In [3]:
import numpy as np

#### Initialisation des variables

In [4]:
nbr_noeud = 4
dist_max = 10
Gamma = 0.5
Q = 0.5
alpha = 1
beta = 1
rho = 0.5
nb_k = 10 # nbr de fourmis
start = 0

#### Création des matrices

In [5]:
mat_dist = np.random.randint(1,dist_max, size = (nbr_noeud,nbr_noeud))
np.fill_diagonal(mat_dist, 0)
print(mat_dist)

[[0 3 6 2]
 [8 0 9 7]
 [5 8 0 3]
 [3 9 3 0]]


In [6]:
mat_phe = np.zeros((nbr_noeud,nbr_noeud))
mat_prob = np.zeros((nbr_noeud,nbr_noeud))
mat_vis = 1/mat_dist
np.fill_diagonal(mat_vis, 0)
mat_visited = [[start] for i in range(nb_k)]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


#### Fonction

In [7]:
#Ville n'ayant pas encore été visitée
def get_ville(mat_visited, nbr_noeud, k):
    all_ville = np.arange(nbr_noeud)
    return np.setdiff1d(all_ville, mat_visited[k])

In [8]:
def get_probij(i,j,k):
    Gamma = np.random.rand()
    mat_probij = Gamma + np.power(mat_phe[i,j], alpha) + np.power(mat_vis[i,j], beta)
    kallowed = get_ville(mat_visited, nbr_noeud, k)
    summ = sum([Gamma + np.power(mat_phe[i,l], alpha) + np.power(mat_vis[i,l], beta) for l in kallowed])
    return mat_probij/summ

In [9]:
def run(i,k,mat_visited):
    while len(mat_visited[k]) != nbr_noeud:
        mat_proba = []
        villeallowed = get_ville(mat_visited, nbr_noeud, k)
        for ville in villeallowed:
            mat_proba.append(get_probij(i,ville,k))
        nextville = villeallowed[np.argmax(np.asarray(mat_proba))]
        mat_visited[k].append(nextville)
        #print(mat_visited[k])
        #print(mat_proba)
        i = nextville
    return(mat_visited[k])

In [10]:
def longueurtrjt(trajet):
    villeav = start
    distance = 0
    for ville in trajet:
        if ville != start:
            distance += mat_dist[villeav,ville]
            villeav = ville
    distance += mat_dist[villeav,start]
    return distance

In [11]:
def run_all(start, k, mat_phe):
    for step in range(nb_k):
        mat_visited = [[start] for i in range(nb_k)]
        mat_visited[k] = run(start,k,mat_visited)
        #print(mat_visited[k])
        villeav = start
        for ville in mat_visited[k]:
            if ville != start:
                mat_phe[villeav, ville] += Q/longueurtrjt(mat_visited[k]) 
                villeav = ville
    return mat_phe

#### Execution

In [12]:
mat_phe = np.zeros((nbr_noeud,nbr_noeud))
for i in range(10):
    mat_phe = rho * run_all(start,i, mat_phe)
    print(mat_phe)

[[0.         0.         0.         0.11904762]
 [0.         0.         0.         0.        ]
 [0.         0.11904762 0.         0.        ]
 [0.         0.         0.11904762 0.        ]]
[[0.         0.         0.         0.17857143]
 [0.         0.         0.         0.        ]
 [0.         0.17857143 0.         0.        ]
 [0.         0.         0.17857143 0.        ]]
[[0.         0.         0.         0.20833333]
 [0.         0.         0.         0.        ]
 [0.         0.20833333 0.         0.        ]
 [0.         0.         0.20833333 0.        ]]
[[0.         0.         0.         0.22321429]
 [0.         0.         0.         0.        ]
 [0.         0.22321429 0.         0.        ]
 [0.         0.         0.22321429 0.        ]]
[[0.         0.         0.         0.23065476]
 [0.         0.         0.         0.        ]
 [0.         0.23065476 0.         0.        ]
 [0.         0.         0.23065476 0.        ]]
[[0.       0.       0.       0.234375]
 [0.       0.   

In [13]:
import pygame

WHITE =     (255, 255, 255)
BLUE =      (  0,   0, 255)
GREEN =     (  0, 255,   0)
RED =       (255,   0,   0)
TEXTCOLOR = (  0,   0,  0)
(width, height) = (200, 300)

running = True

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html


In [14]:
def main():
    global running, screen

    pygame.init()
    screen = pygame.display.set_mode((width, height))
    pygame.display.set_caption("TUFF")
    screen.fill(WHITE)
    pygame.display.update()

    while running:
        ev = pygame.event.get()

        for event in ev:

            if event.type == pygame.MOUSEBUTTONUP:
                drawCircle()
                pygame.display.update()

            if event.type == pygame.QUIT:
                running = False

In [15]:
def getPos():
    pos = pygame.mouse.get_pos()
    return (pos)

def drawCircle():
    pos=getPos()
    pygame.draw.circle(screen, BLUE, (30,30), 20)
    pygame.draw.circle(screen, BLUE, (width - 30,30), 20)
    pygame.draw.circle(screen, BLUE, (30,int(width/2)), 20)
    pygame.draw.circle(screen, BLUE, (width - 30,int(width/2)), 20)
    pygame.draw.circle(screen, GREEN, (int(width/2),height - 30), 20)
def drawlines():
    pygame.draw.line(screen, (0, 0, 255), (int(width/2),int(height/2)), (width - 30,height - 30))

In [ ]:
main()